[Interface]
PrivateKey = ~/.aegis-tunnel/private.key
Port = 9000
Mode = server

[Tunnel]
Keepalive = 30
NATInterface = eth0

[Peer]
PublicKey = aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
AllowedIPs = 0.0.0.0/0
